xdebug.mode=debug
xdebug.log_level=7
;xdebug.start_with_request=yes
;xdebug.start_with_request=trigger
;xdebug.discover_client_host=true
xdebug.remote_handler=dbgp

; Sets the IDE key for your debugger client, replace YOUR_IDE_KEY with your key, e.g., PHPSTORM
xdebug.idekey=PHPSTORM

xdebug.client_host=unix:///run/xdebug-tunnel.sock

xdebug.control_socket=time: 25ms

; Starting a Xdebug session:
; 1. Start Listening for Debug Connections (in your IDE):
; 2. Trigger Debugging in the Browser:
;    Open your web page in the browser.
;    Add a special query parameter to the URL: XDEBUG_SESSION_START=PHPSTORM (or
;    your configured IDE key).
;    For example: https://example.com/yourpage.php?XDEBUG_SESSION_START=PHPSTORM
